"""1

Revision ID: 4461d6f06956
Revises: e5da15633975
Create Date: 2025-06-19 18:24:04.308092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4461d6f06956'
down_revision: Union[str, None] = 'e5da15633975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'product_name',
               existing_type=postgresql.ENUM('oatmeal', 'apple', 'banana', 'bread', 'muffins', 'pancake', 'omelette', 'rice', 'potato_wedges', 'fries', 'glazed_carrot', 'macaroni', 'crusted_chicken', 'cucumber', 'beet', 'sunny_sideup_egg', 'chicken', 'cheese', 'salad', 'orange', 'grapes', 'carrot', 'tomato', 'lettuce', name='product'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('students', 'food_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'food_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('foods', 'product_name',
               existing_type=sa.String(),
               type_=postgresql.ENUM('oatmeal', 'apple', 'banana', 'bread', 'muffins', 'pancake', 'omelette', 'rice', 'potato_wedges', 'fries', 'glazed_carrot', 'macaroni', 'crusted_chicken', 'cucumber', 'beet', 'sunny_sideup_egg', 'chicken', 'cheese', 'salad', 'orange', 'grapes', 'carrot', 'tomato', 'lettuce', name='product'),
               existing_nullable=False)
    # ### end Alembic commands ###
