"""4

Revision ID: 4b1ac84a9bba
Revises: 5b6ece12ab71
Create Date: 2025-06-19 22:15:23.955038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1ac84a9bba'
down_revision: Union[str, None] = '5b6ece12ab71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'students_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'students_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
