"""initial

Revision ID: af7e95b0af53
Revises: 
Create Date: 2025-06-19 21:48:20.443982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7e95b0af53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_name', sa.String(), nullable=False),
    sa.Column('major_description', sa.String(), nullable=True),
    sa.Column('count_students', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_name')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('special_notes', sa.String(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Enum('OATMEAL', 'APPLE', 'BANANA', 'BREAD', 'MUFFINS', 'PANCAKE', 'OMELETTE', 'RICE', 'POTATO_WEDGES', 'FRIES', 'GLAZED_CARROT', 'MACARONI', 'CRUSTED_CHICKEN', 'CUCUMBER', 'BEET', 'SUNNY_SIDEUP_EGG', 'CHICKEN', 'CHEESE', 'SALAD', 'ORANGE', 'GRAPES', 'CARROT', 'TOMATO', 'LETTUCE', name='product'), nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foods')
    op.drop_table('students')
    op.drop_table('majors')
    # ### end Alembic commands ###
